(function(){
'use strict';
const DATA=window.PREVIEW_DATA,D=DATA.insurers,P=DATA.planilla,$=s=>document.querySelector(s),charts=new Map(),seen=new Set(),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const groups={'Medicare Advantage':['Medicare Advantage'],'Medicare Platino':['Medicare Platinum'],Vital:['Government Health Plan (Vital)'],Commercial:['Large Private Group Plans','Small Private Group Plans','Private Individual Plans'],Others:['Government Employees','Government Retirees','Federal Government Employees','Medicare Supplement Plans']};
const state={view:'company',year:'25',company:'mmmhc',group:'All coverages',marketMetric:'prem',rankingMetric:'ni',sort:'p',compare:[]};
const C=window.INSURANCE_CHART_THEME.colors;
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sum=(a,k)=>a.reduce((n,r)=>n+(typeof r[k]==='number'?r[k]:0),0),count=v=>v==null?'Not available':Math.round(v).toLocaleString('en-US'),pct=v=>v==null?'Not available':v.toFixed(1)+'%',delta=v=>v==null?'—':(v>0?'+':'')+v.toFixed(1)+'%',growth=(a,b)=>a==null||b==null||b===0?null:(a/b-1)*100;
const money=v=>v==null?'Not available':(v<0?'−':'')+'$'+(Math.abs(v)/ (Math.abs(v)>=1e9?1e9:Math.abs(v)>=1e6?1e6:Math.abs(v)>=1e3?1e3:1)).toLocaleString('en-US',{maximumFractionDigits:2,minimumFractionDigits:Math.abs(v)>=1e9?2:0})+(Math.abs(v)>=1e9?'B':Math.abs(v)>=1e6?'M':Math.abs(v)>=1e3?'K':'');
const exact=v=>v==null?'Not available':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v),pmpm=(d,k,y)=>d['mm'+y]>0&&d[k+y]!=null?d[k+y]/d['mm'+y]:null,avg=(d,y)=>d['mm'+y]==null?null:d['mm'+y]/12,margin=(d,y)=>d['ni'+y]/d['p'+y]*100;
const year=()=>state.year==='q1'?'Q1 2026':'20'+state.year,key=()=>state.year==='q1'?'Q1_2026':'FY'+state.year,company=()=>D.find(d=>d.id===state.company),name=n=>n==='Medicare Platinum'?'Medicare Platino':n;
const source=()=>state.year==='24'?P.sourceAnnual2024:state.year==='25'?P.sourceAnnual2025:P.sourceQ12026;
const link=(url,t)=>'<a href="'+esc(url)+'" target="_blank" rel="noopener noreferrer">'+esc(t)+' ↗</a>';
const blank=(title,note,action='')=>'<div class="empty"><h2>'+title+'</h2><p>'+note+'</p>'+action+'</div>';
function head(title,note,control=''){return '<div class="page-head"><div><div class="eyebrow">'+year()+' / '+(state.year==='q1'?'January–March · not annualized':'Annual filings')+'</div><h1>'+title+'</h1><p>'+note+'</p></div>'+control+'</div>';}
function kpis(rows){return '<div class="kpis">'+rows.map(r=>'<div class="kpi"><span>'+r[0]+'</span><strong class="'+(r[3]||'')+'">'+r[1]+'</strong><small>'+r[2]+'</small></div>').join('')+'</div>';}
function card(title,note,body,foot='',controls=''){return '<section class="card"><div class="card-head"><div><h2>'+title+'</h2><p>'+note+'</p></div>'+controls+'</div>'+body+(foot?'<div class="source-note">'+foot+'</div>':'')+'</section>';}
function chart(id,extra=''){return '<div class="chart '+extra+'" id="'+id+'" role="img" aria-label="'+id.replace(/-/g,' ')+'"></div>';}
function companySelect(){return '<label class="sr-only" for="company-select">Select insurer</label><select id="company-select">'+D.map(d=>'<option value="'+d.id+'" '+(d.id===state.company?'selected':'')+'>'+esc(d.n)+'</option>').join('')+'</select>';}
function annualNote(){return 'Annual comparisons use FY2024 as filed, not restated prior-year figures in FY2025 statements.';}
function profileThesis(d){if(state.year==='24')return '2024 baseline: '+money(d.p24)+' in premiums and '+money(d.ni24)+' in net '+(d.ni24<0?'loss':'income')+'.';let g=growth(d.p25,d.p24),mg=growth(d.mm25,d.mm24);return 'Premiums '+(g>=0?'rose ':'fell ')+Math.abs(g).toFixed(1)+'%'+(mg==null?'':'; average membership '+(mg>=0?'rose ':'fell ')+Math.abs(mg).toFixed(1)+'%')+'. '+(d.ni24>0&&d.ni25<0?'Profit turned to loss.':d.ni24<0&&d.ni25>0?'The company returned to profit.':d.ni25<0?'The company reported a net loss.':'The company reported positive net income.');}
function spotlight(){const d=company(),y=state.year;return '<aside class="card spotlight"><div class="eyebrow">Selected company · '+year()+'</div><h2>'+esc(d.n)+'</h2><p>'+profileThesis(d)+'</p><span class="figure-label">NET '+(d['ni'+y]<0?'LOSS':'INCOME')+'</span><strong class="figure '+(d['ni'+y]<0?'negative':'positive')+'">'+money(d['ni'+y])+'</strong><dl><div><dt>Premiums</dt><dd>'+money(d['p'+y])+'</dd></div><div><dt>Net income / premiums</dt><dd>'+pct(margin(d,y))+'</dd></div><div><dt>Average members*</dt><dd>'+count(avg(d,y))+'</dd></div></dl><button data-view="company">Open company profile →</button><small class="flat-note">*Member months ÷ 12; eight comparable filers.</small></aside>';}
function companyRows(){const y=state.year,rows=D.slice().sort((a,b)=>state.sort==='growth'?(growth(b.p25,b.p24)-growth(a.p25,a.p24)):state.sort==='members'?((avg(b,y)||0)-(avg(a,y)||0)):b[state.sort+y]-a[state.sort+y]);return '<div class="card table-wrap"><table class="research-table"><thead><tr><th>Compare / Company</th><th>Premiums</th><th>Net income</th><th>NI / premiums</th><th>Average members*</th><th>Premium growth</th><th>Member growth</th></tr></thead><tbody>'+rows.map(d=>'<tr class="'+(d.id===state.company?'selected':'')+'"><td><input class="compare-toggle" type="checkbox" data-compare="'+d.id+'" aria-label="Compare '+esc(d.n)+'" '+(state.compare.includes(d.id)?'checked':'')+'><button data-company="'+d.id+'">'+esc(d.n)+'<small>'+esc(d.pa)+'</small></button></td><td>'+money(d['p'+y])+'</td><td class="'+(d['ni'+y]<0?'negative':'positive')+'">'+money(d['ni'+y])+'</td><td>'+pct(margin(d,y))+'</td><td>'+count(avg(d,y))+'</td><td>'+(y==='25'?'<span class="mini-change '+(d.p25<d.p24?'negative':'')+'">'+delta(growth(d.p25,d.p24))+'</span>':'—')+'</td><td>'+(y==='25'?delta(growth(d.mm25,d.mm24)):'—')+'</td></tr>').join('')+'</tbody></table></div>';}
const rankingLabels={ni:'Profit / loss',p:'Premiums',members:'Members',growth:'Growth'};
function rankingValue(d,y=state.year){return state.rankingMetric==='members'?avg(d,y):state.rankingMetric==='growth'?(y==='25'?growth(d.p25,d.p24):null):d[state.rankingMetric+y];}
function rankingFormat(v){return v==null?'Not reported':state.rankingMetric==='members'?count(v):state.rankingMetric==='growth'?delta(v):money(v);}
function rankingControls(){return '<div class="chart-controls" role="group" aria-label="Compare insurers by">'+Object.entries(rankingLabels).map(([k,v])=>'<button data-ranking="'+k+'" aria-pressed="'+(state.rankingMetric===k)+'">'+v+'</button>').join('')+'</div>';}
function portfolio(){
 if(state.year==='q1')return head('Company overview','Quarterly data availability')+blank('Q1 insurer statements are not available in this dataset.','Market-wide premiums, claims paid and reported covered lives are available for January–March 2026. Annual insurer results are kept in their own periods.','<button data-view="markets">Explore Q1 coverage markets →</button>');
 const y=state.year,mm=D.filter(d=>d['mm'+y]!=null),titles={ni:['Insurer profits and losses','Reported net income, ranked from highest to lowest.'],p:['Premiums, company by company','Compare the financial scale of nine insurer legal entities.'],members:['Membership, company by company','Average monthly membership, using the same definition for each Health filer.'],growth:['Which insurers are growing?','Compare the change in annual premiums.']},t=titles[state.rankingMetric];
 const notes={ni:'Profits to the right. Losses to the left.',p:'Longer bars mean more premiums.',members:'Member months ÷ 12. MCS Life has no comparable figure.',growth:y==='25'?'2025 versus 2024. Increases to the right; declines to the left.':'A 2023 baseline is required to calculate 2024 growth.'};
 return head(t[0],t[1])+kpis([['Statutory premiums',money(sum(D,'p'+y)),y==='25'?delta(growth(sum(D,'p25'),sum(D,'p24')))+' vs 2024':'Nine insurers · full year'],['Combined net income',money(sum(D,'ni'+y)),'Profits and losses combined',sum(D,'ni'+y)<0?'negative':'positive'],['Average members*',count(sum(mm,'mm'+y)/12),'Eight Health filers · excludes MCS Life'],['Profitable insurers',D.filter(d=>d['ni'+y]>0).length+' / 9','Positive reported net income']])+ '<div class="analysis-grid">'+card({ni:'Net income by insurer',p:'Premiums by insurer',members:'Average members by insurer',growth:'Premium growth by insurer'}[state.rankingMetric],notes[state.rankingMetric],rankingControls()+chart('portfolio-chart'),'Select a bar or company name to see its snapshot. Annual source filings and exact values are available under Sources and Data CSV.')+spotlight()+'</div><div class="section-head"><div><h2>Company comparison</h2><p>Choose up to three companies for a side-by-side review.</p></div><div class="toolbar"><label class="sr-only" for="sort">Sort companies</label><select id="sort">'+[['p','Premiums'],['ni','Net income'],['members','Average members'],['growth','Premium growth 2024–25']].filter(r=>y==='25'||r[0]!=='growth').map(r=>'<option value="'+r[0]+'" '+(state.sort===r[0]?'selected':'')+'>'+r[1]+'</option>').join('')+'</select><button data-action="compare">Compare ('+state.compare.length+')</button></div></div>'+companyRows()+'<p class="flat-note">*Average membership = annual member months ÷ 12. Growth is 2024–2025; no 2023 baseline is supplied. Statutory insurer premiums and OCS market totals have different scopes.</p>';
}
function financeTable(d){const rows=[['Net premiums','p'],['Net income','ni'],['Total medical expenses','tm'],['Administrative expenses','a']];return '<table class="financial-table"><thead><tr><th>Statutory measure</th><th>2024</th><th>2025</th></tr></thead><tbody>'+rows.map(([n,k])=>'<tr><td>'+n+'</td><td>'+money(d[k+'24'])+'</td><td class="'+(d[k+'25']<0?'negative':'')+'">'+money(d[k+'25'])+'</td></tr>').join('')+'<tr><td>NI / premiums</td><td>'+pct(margin(d,'24'))+'</td><td>'+pct(margin(d,'25'))+'</td></tr><tr><td>Average members</td><td>'+count(avg(d,'24'))+'</td><td>'+count(avg(d,'25'))+'</td></tr></tbody></table>';}
function coverageFor(d,y=state.year){return window.COMPANY_COVERAGE?.entities?.[d.id]?.periods?.['FY'+y]||(d.id==='mmmhc'?window.MMM_COVERAGE?.periods?.['FY'+y]:null);}
function coverageGroupRows(v){return Object.entries(groups).map(([group,names])=>({group,prem:sum(v.coverage.filter(r=>names.includes(r.t)),'prem')})).filter(r=>r.prem>0).sort((a,b)=>b.prem-a.prem);}
function sourceCompanyMix(d){
 const v=coverageFor(d);if(!v)return card('3. Which markets does it serve?','Reported business: '+esc(d.sg),'<p class="story-copy">The company-level coverage split is not yet verified.</p>');
 const rows=v.coverage.filter(r=>['prem','lives','claims'].some(k=>typeof r[k]==='number'&&r[k]!==0)),g=coverageGroupRows(v),total=sum(v.coverage,'prem'),top=g[0];
 return card('3. Which markets does it serve?',year()+' · company-specific coverage',
 '<p class="story-answer">'+(top?'<strong>'+top.group+'</strong> accounts for <strong>'+pct(top.prem/total*100)+'</strong> of this company’s reported coverage premiums.':'No separate coverage amounts are reported.')+'</p>'+chart('company-mix-chart','mix-chart')+
 '<details class="source-detail"><summary>See reported premiums, claims and lives by category</summary><div class="table-wrap"><table class="financial-table"><thead><tr><th>Coverage</th><th>Premiums</th><th>Claims paid</th><th>Reported lives</th></tr></thead><tbody>'+rows.map(r=>'<tr><td>'+name(r.t)+'</td><td>'+money(r.prem)+'</td><td>'+money(r.claims)+'</td><td>'+count(r.lives)+'</td></tr>').join('')+'</tbody></table></div><button class="coverage-download" data-action="coveragecsv">Download coverage data CSV</button></details>'+
 (d.id==='mmmhc'?'<p class="source-note">MMM is reported entirely under Medicare Advantage in 2024; the 2025 report separates Advantage, Platino and Government Retirees. This is not proof of member migration.</p>':''),
 link(v.sourceUrl||source(),'OCS coverage report, pages 1–3')+' · Reported lives are different from average membership. Commercial and Others group source categories. Claims-only adjustments do not establish an active product. Coverage percentages use the Planilla premium total, which can differ from statutory premiums.');
}
function changeSentence(a,b,unit){if(a==null||b==null)return 'Comparable figures are not available.';let diff=b-a;return unit+' '+(diff>0?'increased by ':diff<0?'decreased by ':'was unchanged')+(diff===0?'.':(['Average membership','Reported lives'].includes(unit)?count(Math.abs(diff)):money(Math.abs(diff)))+' ('+Math.abs(growth(b,a)).toFixed(1)+'%) from 2024 to 2025.');}
function earningsStory(d){if(d.ni24>=0&&d.ni25<0)return 'The company moved from a '+money(d.ni24)+' profit to a '+money(Math.abs(d.ni25))+' loss.';if(d.ni24<0&&d.ni25>=0)return 'The company moved from a '+money(Math.abs(d.ni24))+' loss to a '+money(d.ni25)+' profit.';let diff=d.ni25-d.ni24;return d.ni25<0?'The loss '+(diff>0?'narrowed':'widened')+' by '+money(Math.abs(diff))+'.':'Net income '+(diff>=0?'increased':'decreased')+' by '+money(Math.abs(diff))+'.';}
function reportedLives(d,y){return coverageFor(d,y)?.totals.lives??null;}
function companySummary(d){const y=state.year,other=y==='25'?'24':'25';return '<div class="company-summary">'+[
 ['Net '+(d['ni'+y]<0?'loss':'income'),money(d['ni'+y]),'20'+other+': '+money(d['ni'+other]),'summary-primary '+(d['ni'+y]<0?'negative':'')],
 ['Premiums',money(d['p'+y]),'20'+other+': '+money(d['p'+other]),''],
 ['Reported covered lives',count(reportedLives(d,y)),'20'+other+': '+count(reportedLives(d,other)),'']
 ].map(r=>'<div class="'+r[3]+'"><span>'+r[0]+'</span><strong>'+r[1]+'</strong><small>'+r[2]+'</small></div>').join('')+'</div>';}
function profile(){
 const d=company();const picker='<div class="company-picker"><label for="company-select">Choose an insurer</label><select id="company-select">'+D.map(x=>'<option value="'+x.id+'" '+(x.id===d.id?'selected':'')+'>'+esc(x.n)+'</option>').join('')+'</select><span>Financial results, membership and coverage in one place.</span></div>';
 if(state.year==='q1')return picker+head(d.n,'Q1 2026 company review')+blank('The quarterly company review is not yet available.','The current Q1 dataset contains market-wide premiums, claims paid and reported lives. Choose 2024 or 2025 for this company’s full annual review.','<button data-view="markets">Open Q1 market overview →</button>');
 const y=state.year,mm=avg(d,'25'),premChange=changeSentence(d.p24,d.p25,'Premiums'),memberChange=changeSentence(reportedLives(d,'24'),reportedLives(d,'25'),'Reported lives');
 const annualLinks=link(d.s24,'2024 filing')+' · '+link(d.s25,'2025 filing');
 const question=d.ni25<0?'What explains the reported loss, and what would restore profitability?':'How much of the reported profit is recurring, and can it be sustained?';
 return picker+head(d.n,esc(d.le)+' · '+esc(d.pa))+
 '<p class="company-thesis">'+(y==='25'?earningsStory(d)+' '+premChange:'2024 annual review. The comparisons below also show how the company changed in 2025.')+'</p>'+companySummary(d)+
 '<div class="story-grid">'+
 card('1. Is it making money?','Net income · 2024 and 2025',chart('earnings-chart','story-chart')+'<p class="story-copy">'+earningsStory(d)+'</p>',annualLinks,'')+
 card('2. Is it covering more lives?','Reported covered lives · 2024 and 2025',chart('members-chart','story-chart')+'<p class="story-copy">'+memberChange+'</p>','OCS Planilla counts. These are not average membership or deduplicated unique people.')+'</div>'+
 
 sourceCompanyMix(d)+
 '<section class="card operating-review"><div class="card-head"><div><h2>4. What changed in operating costs?</h2><p>'+premChange+'</p></div></div><p class="story-answer">'+(d.mm25==null?'Comparable medical and administrative expenses per member are not available for this filing.':'The chart compares premium income, medical expenses and administration for an average member-month in each year.')+'</p>'+chart('unit-chart')+'<p class="source-note">Amounts divided by member months. Medical expenses and administration are not a complete explanation of net income; other statement items also contribute.</p></section>'+
 '<section class="diligence-note"><div><div class="eyebrow">What to investigate next</div><h2>'+question+'</h2></div><p>Capital requirements, reserve adequacy, regulatory history, contract concentration and normalized earnings still require supporting evidence.</p></section>'+
 '<details class="source-detail detailed-financials"><summary>Full financial comparison, balance sheet and sources</summary><div class="split">'+card('Annual financial comparison','2024 and 2025 as filed',financeTable(d),annualNote()+' '+annualLinks)+card('Capital & balance sheet',y==='25'?'FY2025 · reported values':'FY2024 · not verified in this dataset',y==='25'?'<table class="financial-table"><tbody>'+[['Admitted assets',d.ast],['Liabilities',d.lia],['Capital & surplus',d.eq]].map(r=>'<tr><td>'+r[0]+'</td><td>'+exact(r[1])+'</td></tr>').join('')+'</tbody></table>':'<p class="story-copy">No verified FY2024 balance snapshot is available here.</p>','Capital & surplus is not an acquisition price or an RBC ratio.')+'</div></details>'+
 '<div class="foot-actions"><button data-view="portfolio">Compare this insurer with the others</button><button data-action="export">Download company data</button><button data-action="print">Print company review</button></div>';
}
function drawCompanyStory(){
 const d=company();
 function pair(id,values,format){
  if(values.some(v=>v==null)){document.getElementById(id).innerHTML='<div class="story-unavailable">Comparable reported lives are unavailable.<br><small>Consult the original coverage reports</small></div>';return;}
  put(id,{grid:{left:23,right:23,top:42,bottom:40},xAxis:{...axis('category'),data:['2024','2025'],axisLabel:{color:C.ink,fontSize:13},axisLine:{show:true,lineStyle:{color:C.grid}}},yAxis:{type:'value',min:Math.min(0,...values)*1.3,max:Math.max(0,...values)*1.28||1,show:false},tooltip:{formatter:p=>p.name+': '+format(p.value)},series:[{type:'bar',barMaxWidth:78,data:values.map((v,i)=>({value:v,itemStyle:{color:i===0?C.prior:v<0?C.loss:C.teal,borderRadius:2},label:{show:true,position:v<0?'bottom':'top',formatter:format(v),distance:9,fontSize:16,fontWeight:600,color:C.ink}})),markLine:values.some(v=>v<0)?{silent:true,symbol:'none',label:{show:false},lineStyle:{color:'#8f918e',type:'solid',width:1},data:[{yAxis:0}]}:undefined}]});
 }
 pair('earnings-chart',[d.ni24,d.ni25],money);pair('members-chart',[reportedLives(d,'24'),reportedLives(d,'25')],count);
 const v=coverageFor(d);if(v){const rows=coverageGroupRows(v);$('#company-mix-chart').style.height=Math.max(135,rows.length*44+55)+'px';const mobile=$('#company-mix-chart').clientWidth<500,total=sum(rows,'prem');put('company-mix-chart',{grid:{left:mobile?130:185,right:mobile?77:125,top:20,bottom:25},xAxis:{type:'value',show:false,min:0,max:100},yAxis:{...axis('category'),inverse:true,data:rows.map(r=>r.group),axisLabel:{color:C.ink,fontSize:mobile?11:13}},tooltip:{formatter:p=>'<b>'+p.name+'</b><br>'+year()+' premiums: '+exact(rows[p.dataIndex].prem)},series:[{type:'bar',barMaxWidth:23,itemStyle:{color:C.teal,borderRadius:2},data:rows.map(r=>({name:r.group,value:r.prem/total*100,label:{show:true,position:'right',formatter:pct(r.prem/total*100),color:C.ink,fontSize:12}}))}]});}
 drawUnit();
}
function selectedCoverage(periodKey){return P.coverage[periodKey].filter(r=>state.group==='All coverages'||groups[state.group].includes(r.t));}
function coverageMetric(){return {prem:'Premiums written',claims:'Claims paid',lives:'Reported covered lives'}[state.marketMetric];}
function marketFormat(v){return state.marketMetric==='lives'?count(v):money(v);}
function marketRows(){let current=selectedCoverage(key()),prior=selectedCoverage('FY24');return '<div class="card table-wrap"><table class="research-table"><thead><tr><th>Coverage</th>'+(state.year==='q1'?'<th>Q1 2026 premiums</th><th>Claims paid</th><th>Covered lives</th>':'<th>2024 '+coverageMetric()+'</th><th>2025 '+coverageMetric()+'</th><th>Change</th>')+'<th>'+year()+' paid claims / premiums</th></tr></thead><tbody>'+current.map(r=>{let a=prior.find(a=>a.t===r.t),b=P.coverage.FY25.find(a=>a.t===r.t);return '<tr><td>'+name(r.t)+'</td>'+(state.year==='q1'?'<td>'+money(r.prem)+'</td><td>'+money(r.claims)+'</td><td>'+count(r.lives)+'</td>':'<td>'+marketFormat(a[state.marketMetric])+'</td><td>'+marketFormat(b[state.marketMetric])+'</td><td>'+delta(growth(b[state.marketMetric],a[state.marketMetric]))+'</td>')+'<td style="background:rgba(146,61,58,'+Math.max(.02,(r.claims/r.prem-.6)*.28)+')">'+pct(r.claims/r.prem*100)+'</td></tr>';}).join('')+'</tbody></table></div>';}
function markets(){const rows=selectedCoverage(key()),prem=sum(rows,'prem'),claims=sum(rows,'claims'),lives=sum(rows,'lives');return head('Follow the coverage markets','Medicare Advantage · Medicare Platino · Vital · Commercial · Others')+'<div class="coverage-filters" role="group" aria-label="Coverage group">'+['All coverages',...Object.keys(groups)].map(g=>'<button data-group="'+g+'" aria-pressed="'+(g===state.group)+'">'+g+'</button>').join('')+'</div>'+kpis([['Premiums written',money(prem),state.group],['Claims paid',money(claims),state.year==='q1'?'Three months only':'Full year '+year()],['Reported covered lives',count(lives),'OCS counts; not deduplicated people'],['Paid claims / premiums',pct(claims/prem*100),'Not statutory MLR']])+card(state.year==='q1'?'Q1 coverage snapshot':'How the reported market changed',state.year==='q1'?'January–March 2026 · not annualized':'Full-year 2024 → 2025 · '+state.group,(state.year==='q1'?'':'<div class="legend"><span><i></i>2024</span><span><i class="current"></i>2025</span></div>')+chart('market-chart','coverage-chart'),link(source(),'OCS '+year()+' report')+' · Values and changes are compared below. Export CSV for exact amounts.','<label class="sr-only" for="market-metric">Coverage metric</label><select id="market-metric">'+[['prem','Premiums'],['claims','Claims paid'],['lives','Covered lives']].map(r=>'<option value="'+r[0]+'" '+(state.marketMetric===r[0]?'selected':'')+'>'+r[1]+'</option>').join('')+'</select>')+(state.year==='q1'?'':'<div class="caution"><strong>Read category changes carefully.</strong> The reports classify MMM’s business differently in 2024 and 2025. Advantage, Platino and Government Retirees changes include reporting differences; they are not proof of organic growth. '+link(P.sourceAnnual2024+'#page=1','2024 source')+' · '+link(P.sourceAnnual2025+'#page=1','2025 source')+'</div>')+'<div class="section-head"><div><h2>Coverage comparison</h2><p>Commercial and Others are navigation groups. Every underlying category remains visible.</p></div></div>'+marketRows()+'<p class="flat-note">Paid claims are different from incurred medical expenses and net income. FY2025 claims use the detailed report total, $196,246 above its summary page. Covered lives include the reporting scopes of the source, including dental coverage.</p>';}
const base=()=>window.INSURANCE_CHART_THEME.base(reduced),axis=window.INSURANCE_CHART_THEME.axis;
function put(id,opt,onClick){let el=$('#'+id);if(!el)return;if(!window.echarts){el.innerHTML=blank('Chart unavailable','Use the figures and tables below. Reload the page to retry.');return;}let c=echarts.init(el,null,{renderer:'svg'});charts.set(id,c);let b=base();b.animation=!reduced&&!seen.has(id);seen.add(id);c.setOption({...b,...opt,tooltip:{...b.tooltip,...opt.tooltip},aria:{enabled:true,label:{description:el.closest('.card').querySelector('h2').textContent+'. '+year()+'. Values and sources are available in the accompanying table.'}}});if(onClick)c.on('click',onClick);}
function drawPortfolio(){
 const el=$('#portfolio-chart'),y=state.year,metric=state.rankingMetric,mobile=el.clientWidth<500;
 if(metric==='growth'&&y==='24'){el.innerHTML=blank('A prior-year baseline is needed.','The dataset does not include 2023 filings. Select 2025 to compare 2025 premiums with 2024.');return;}
 const rows=D.slice().sort((a,b)=>{const va=rankingValue(a),vb=rankingValue(b);return va==null?1:vb==null?-1:vb-va;});
 const scale=metric==='ni'?1e6:metric==='p'?1e9:metric==='members'?1000:1;
 const values=rows.map(d=>rankingValue(d));
 const all=D.flatMap(d=>['24','25'].map(yr=>rankingValue(d,yr))).filter(v=>v!=null).map(v=>v/scale);
 const lo=Math.min(0,...all),hi=Math.max(0,...all),tickUnit=metric==='ni'?25:metric==='p'?1:metric==='members'?100:10,lower=Math.floor(lo/tickUnit)*tickUnit,upper=Math.max(tickUnit,Math.ceil(hi/tickUnit)*tickUnit);
 const grid={left:mobile?127:165,right:mobile?69:105,top:15,bottom:45};
 const graphic=rows.flatMap((d,i)=>rankingValue(d)==null?[{type:'text',right:mobile?10:22,top:15+(i+.5)*(el.clientHeight-60)/rows.length-6,style:{text:'Not reported',fill:C.muted,fontSize:11,fontFamily:'Arial'}}]:[]);
 put('portfolio-chart',{
  grid,graphic,
  xAxis:{...axis('value'),min:lower,max:upper,splitNumber:mobile?2:4,name:metric==='ni'?'USD millions':metric==='p'?'USD billions':metric==='members'?'Members · thousands':'Premium change · %',nameLocation:'middle',nameGap:28,nameTextStyle:{color:C.muted,fontSize:11},axisLabel:{color:C.muted,fontSize:10,showMaxLabel:!mobile,formatter:v=>metric==='growth'?Math.round(v)+'%':metric==='members'?Math.round(v)+'K':(v<0?'−':'')+'$'+Math.abs(v).toLocaleString('en-US',{maximumFractionDigits:1})}},
  yAxis:{...axis('category'),inverse:true,data:rows.map(d=>d.n),triggerEvent:true,axisLabel:{color:C.ink,fontSize:mobile?11:12,margin:mobile?11:16,width:mobile?111:147,overflow:'break',lineHeight:15,formatter:v=>v===company().n?'{selected|'+v+'}':v,rich:{selected:{fontWeight:700,color:C.ink,fontSize:mobile?11:12,lineHeight:15}}}},
  tooltip:{trigger:'item',formatter:p=>{const d=rows[p.dataIndex],v=rankingValue(d);return '<b>'+esc(d.n)+'</b><br>'+year()+' '+rankingLabels[metric]+': '+(v==null?'Not reported':metric==='members'?count(v):metric==='growth'?delta(v):exact(v))+(metric==='ni'?'<br>Net income / premiums: '+pct(margin(d,y)):'');}},
  series:[{type:'bar',barMaxWidth:mobile?17:21,data:rows.map((d,i)=>({name:d.n,entity:d.id,value:values[i]==null?null:values[i]/scale,itemStyle:{color:values[i]<0?C.loss:C.teal,borderColor:d.id===state.company?C.ink:'transparent',borderWidth:d.id===state.company?1.5:0,borderRadius:1},label:{show:true,position:'right',distance:7,color:values[i]<0?C.loss:C.ink,fontWeight:d.id===state.company?700:500,fontSize:mobile?10:12,formatter:rankingFormat(values[i])}})),emphasis:{itemStyle:{borderColor:C.ink,borderWidth:1.5}},markLine:lo<0?{silent:true,symbol:'none',label:{show:false},lineStyle:{color:'#9B9A94',width:1,type:'solid'},data:[{xAxis:0}]}:undefined}]
 },p=>{const d=p.data?.entity?D.find(d=>d.id===p.data.entity):p.componentType==='yAxis'?D.find(d=>d.n===p.value):null;if(d){state.company=d.id;sync();render();}});
}
function drawUnit(){const d=company();if(d.mm25==null||d.mm24==null){$('#unit-chart').innerHTML=blank('No comparable PMPM data','MCS Life does not report comparable member-month and expense fields in this dataset.');return;}const ks=['p','tm','a'];put('unit-chart',{grid:{left:110,right:75,top:30,bottom:45},legend:{bottom:0,textStyle:{color:C.muted},data:['2024','2025']},xAxis:{...axis('value'),axisLabel:{color:C.muted,formatter:v=>'$'+v}},yAxis:{...axis('category'),inverse:true,data:['Premium','Medical','Administration']},tooltip:{trigger:'axis',formatter:ps=>'<b>'+ps[0].axisValue+' / member / month</b><br>'+ps.map(p=>p.seriesName+': '+exact(p.value)).join('<br>')},series:['24','25'].map((y,i)=>({name:'20'+y,type:'bar',barMaxWidth:19,itemStyle:{color:i?C.teal:C.prior,borderRadius:3},label:{show:true,position:'right',fontSize:11,color:C.ink,formatter:p=>exact(p.value)},data:ks.map(k=>pmpm(d,k,y))}))});}
function wrap(v){const words=name(v).split(' '),lines=[''];words.forEach(w=>{let i=lines.length-1;if((lines[i]+' '+w).length>21&&lines[i])lines.push(w);else lines[i]+=(lines[i]?' ':'')+w;});return lines.join('\n');}
function drawMarket(){let selected=selectedCoverage(key()),metric=state.marketMetric,rows=selected.slice().sort((a,b)=>b[metric]-a[metric]),mobile=$('#market-chart').clientWidth<500;const lookup=(k,t)=>P.coverage[k].find(r=>r.t===t)[metric],max=Math.max(...rows.map(r=>Math.max(lookup('FY24',r.t),lookup('FY25',r.t),r[metric])));let options={grid:{left:mobile?128:190,right:mobile?55:100,top:20,bottom:40},xAxis:{...axis('value'),min:0,max:state.year==='q1'?Math.max(...rows.map(r=>r[metric]))*1.1:max*1.08,axisLabel:{color:C.muted,fontSize:10,formatter:v=>metric==='lives'?(v/1000).toFixed(0)+'K':money(v)},splitNumber:3},yAxis:{...axis('category'),inverse:true,data:rows.map(r=>r.t),axisLabel:{color:C.ink,fontSize:mobile?10:12,lineHeight:14,formatter:wrap}},tooltip:{trigger:'axis',formatter:ps=>'<b>'+name(ps[0].axisValue)+'</b><br>'+ps.map(p=>p.seriesName+': '+(metric==='lives'?count(p.value):exact(p.value))).join('<br>')},series:(state.year==='q1'?['Q1_2026']:['FY24','FY25']).map((k,i)=>({name:k==='Q1_2026'?'Q1 2026':k==='FY24'?'2024':'2025',type:'bar',barMaxWidth:state.year==='q1'?22:14,itemStyle:{color:k==='FY24'?C.prior:C.teal,borderRadius:2},label:{show:k!=='FY24',position:'right',fontSize:mobile?9:11,color:C.ink,formatter:p=>marketFormat(p.value)},data:rows.map(r=>lookup(k,r.t))}))};put('market-chart',options);}
function readURL(){let u=new URL(location.href);state.view=['portfolio','company','markets'].includes(u.searchParams.get('view'))?u.searchParams.get('view'):'company';state.year=['24','25','q1'].includes(u.searchParams.get('year'))?u.searchParams.get('year'):'25';state.company=D.some(d=>d.id===u.searchParams.get('company'))?u.searchParams.get('company'):'mmmhc';let g=u.searchParams.get('group');state.group=groups[g]?g:'All coverages';let m=u.searchParams.get('measure');state.marketMetric=['prem','claims','lives'].includes(m)?m:'prem';let ranking=u.searchParams.get('ranking');state.rankingMetric=Object.hasOwn(rankingLabels,ranking)?ranking:'ni';}
function sync(){let u=new URL(location.href);['view','year','company','group'].forEach(k=>u.searchParams.set(k,state[k]));u.searchParams.set('measure',state.marketMetric);u.searchParams.set('ranking',state.rankingMetric);history.pushState(null,'',u);}
function render(){if(state.year==='24'&&state.sort==='growth')state.sort='p';charts.forEach(c=>c.dispose());charts.clear();document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.view===state.view));document.querySelectorAll('[role=tab]').forEach(b=>{let on=b.dataset.year===state.year;b.setAttribute('aria-selected',on);b.tabIndex=on?0:-1;});$('#workspace').dataset.view=state.view;$('#workspace').setAttribute('aria-labelledby','year-'+state.year);$('#workspace').innerHTML=state.view==='portfolio'?portfolio():state.view==='company'?profile():markets();if(state.year!=='q1'){if(state.view==='portfolio')drawPortfolio();if(state.view==='company')drawCompanyStory();}if(state.view==='markets')drawMarket();$('#status').textContent=year()+'. '+({portfolio:'Company overview',company:company().n+' profile',markets:state.group})[state.view]+' loaded.';}
function modal(title,body){$('#modal-title').textContent=title;$('#modal-body').innerHTML=body;$('#modal').showModal();}
function showSources(){modal('Sources & definitions','<p>Annual company financials and market coverage reports have separate scopes. Reported facts and calculated metrics remain distinct.</p><h3>OCS market coverage</h3><ul>'+[[P.sourceAnnual2024,'2024 report'],[P.sourceAnnual2025,'2025 report'],[P.sourceQ12026,'Q1 2026 report']].map(r=>'<li>'+link(r[0],r[1])+'</li>').join('')+'</ul><h3>Selected insurer: '+esc(company().n)+'</h3><p>'+link(company().s24,'2024 statutory filing')+' · '+link(company().s25,'2025 statutory filing')+'</p><p>Average membership = member months ÷ 12. PMPM = annual amount ÷ member months. Net income / premiums is not a revenue-based margin or regulatory MLR.</p><p>FY2025 balances are as reported in the existing Observatory. RBC, reserve adequacy, compliance clearance and acquisition valuation remain unverified.</p><p>'+annualNote()+'</p><p>'+link('company-coverage.json','Nine-company coverage data and sources')+' · '+link('coverage-audit.json.gz','Download full extraction audit')+'</p>');}
function compareModal(){if(state.year==='q1'){toast('Quarterly insurer comparisons are unavailable.');return;}let ds=D.filter(d=>state.compare.includes(d.id));if(ds.length<2){toast('Select two or three companies in the comparison table.');return;}let y=state.year,rows=[['Premiums',d=>money(d['p'+y])],['Net income',d=>money(d['ni'+y])],['NI / premiums',d=>pct(margin(d,y))],['Average members',d=>count(avg(d,y))],['Premium PMPM',d=>exact(pmpm(d,'p',y))],['Medical PMPM',d=>exact(pmpm(d,'tm',y))],['Admin PMPM',d=>exact(pmpm(d,'a',y))]];if(y==='25')rows.push(['Premium growth',d=>delta(growth(d.p25,d.p24))],['Member growth',d=>delta(growth(d.mm25,d.mm24))]);modal(year()+' · Company comparison','<div class="table-wrap"><table class="financial-table"><thead><tr><th>Measure</th>'+ds.map(d=>'<th>'+esc(d.n)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr><td>'+r[0]+'</td>'+ds.map(d=>'<td>'+r[1](d)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div><p>Same reporting year and definitions. MCS Life has no comparable membership or medical/admin expense fields.</p>');}
function toast(t){let n=document.createElement('div');n.className='toast';n.setAttribute('role','status');n.textContent=t;document.body.append(n);setTimeout(()=>n.remove(),4000);}

async function exportPNG(){
 const entry=[...charts.entries()][0];if(!entry){toast('No chart is available in this view.');return;}
 try{const [id,c]=entry,im=new Image();im.src=c.getDataURL({type:'svg',backgroundColor:'#fff'});await im.decode();
 const scale=2,canvas=document.createElement('canvas'),width=Math.max(c.getWidth(),760),height=c.getHeight()+125;canvas.width=width*scale;canvas.height=height*scale;const cx=canvas.getContext('2d');cx.scale(scale,scale);cx.fillStyle='#fff';cx.fillRect(0,0,width,height);cx.fillStyle=C.ink;cx.font='600 21px Arial';cx.fillText('PR Insurance Observatory · '+year(),22,33);cx.font='14px Arial';cx.fillText(document.getElementById(id).closest('.card').querySelector('h2').textContent,22,59);cx.drawImage(im,(width-c.getWidth())/2,75,c.getWidth(),c.getHeight());cx.fillStyle=C.muted;cx.font='11px Arial';cx.fillText('Source: public OCS filings · '+(state.view==='markets'?state.group:state.view==='company'?company().n:'Nine insurer legal entities'),22,height-20);const a=document.createElement('a');a.href=canvas.toDataURL('image/png');a.download='PR-insurance-'+state.view+'-'+year().replace(/ /g,'-')+'.png';a.click();toast('Chart exported as PNG.');}catch(err){toast('Chart export unavailable. Use Print to save this view.');}
}
function exportCoverageCSV(){
 const d=company(),rows=[['Company','Year','Coverage','Group','Premiums USD','Claims paid USD','Reported lives','Source']];
 for(const y of ['24','25']){const v=coverageFor(d,y);if(v)v.coverage.forEach(r=>rows.push([d.n,'20'+y,name(r.t),r.group,r.prem,r.claims,r.lives,v.sourceUrl]));}
 const body='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n'),url=URL.createObjectURL(new Blob([body],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=d.id+'-coverage-2024-2025.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('Company coverage data exported.');
}
function exportCSV(){let rows;if(state.view==='markets'){rows=[['Period','Group','Coverage','Premiums written USD','Claims paid USD','Reported covered lives','Source']];let keys=state.year==='q1'?['Q1_2026']:['FY24','FY25'];keys.forEach(k=>selectedCoverage(k).forEach(r=>rows.push([k,Object.keys(groups).find(g=>groups[g].includes(r.t)),name(r.t),r.prem,r.claims,r.lives,r.src])));}else{if(state.year==='q1'){toast('No quarterly company financial data to export.');return;}rows=[['Company','Legal entity','Period','Premiums USD','Net income USD','Medical USD','Admin USD','Member months','Average members calculated','Premium PMPM calculated','Source']];let ds=state.view==='company'?[company()]:D;ds.forEach(d=>['24','25'].forEach(y=>rows.push([d.n,d.le,'20'+y,d['p'+y],d['ni'+y],d['tm'+y],d['a'+y],d['mm'+y],avg(d,y),pmpm(d,'p',y),d['s'+y]])));}let s='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n'),u=URL.createObjectURL(new Blob([s],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download='PR-insurance-'+state.view+'-'+year().replace(/ /g,'-')+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),10000);toast('Source-backed data exported.');}
document.addEventListener('click',e=>{let b=e.target.closest('[data-view],[data-year],[data-company],[data-group],[data-ranking],[data-action]');if(!b)return;if(b.dataset.action){({sources:showSources,close:()=>$('#modal').close(),compare:compareModal,export:exportCSV,print:()=>window.print(),png:exportPNG,coveragecsv:exportCoverageCSV})[b.dataset.action]?.();return;}if(b.dataset.view)state.view=b.dataset.view;if(b.dataset.year)state.year=b.dataset.year;if(b.dataset.company){state.company=b.dataset.company;state.view='company';}if(b.dataset.group)state.group=b.dataset.group;if(b.dataset.ranking)state.rankingMetric=b.dataset.ranking;sync();render();if(b.dataset.year)$('#year-'+state.year).focus({preventScroll:true});if(b.dataset.view||b.dataset.company)window.scrollTo({top:0,behavior:'instant'});});
document.addEventListener('change',e=>{if(e.target.dataset.compare){let id=e.target.dataset.compare;if(e.target.checked&&state.compare.length>=3){e.target.checked=false;toast('Compare up to three companies at a time.');return;}state.compare=e.target.checked?[...state.compare,id]:state.compare.filter(v=>v!==id);let b=$('[data-action=compare]');if(b)b.textContent='Compare ('+state.compare.length+')';return;}if(e.target.id==='company-select'){state.company=e.target.value;sync();render();}if(e.target.id==='sort'){state.sort=e.target.value;render();}if(e.target.id==='market-metric'){state.marketMetric=e.target.value;sync();render();}});
document.addEventListener('keydown',e=>{if(!e.target.matches('[role=tab]'))return;let a=[...document.querySelectorAll('[role=tab]')],i=a.indexOf(e.target),j=e.key==='ArrowRight'?(i+1)%3:e.key==='ArrowLeft'?(i+2)%3:e.key==='Home'?0:e.key==='End'?2:null;if(j!=null){e.preventDefault();a[j].click();}});let timer;window.addEventListener('resize',()=>{clearTimeout(timer);timer=setTimeout(()=>{charts.forEach(c=>c.resize());},120);});window.addEventListener('popstate',()=>{readURL();render();});readURL();window.InsuranceResearch={state,render,charts,groups,avg,pmpm,selectedCoverage};render();
})();
