(function(){
'use strict';
const $=s=>document.querySelector(s),data=window.PREVIEW_DATA,periods={'24':{key:'FY24',label:'2024',note:'January–December 2024'},'25':{key:'FY25',label:'2025',note:'January–December 2025'},q1:{key:'Q1_2026',label:'Q1 2026',note:'January–March 2026 · Not annualized'}};
const state={period:'25',metric:'p'},charts=new Map(),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const color={teal:'#59d5bc',neutral:'#a3b4c1',ink:'#f0f4f6',muted:'#a9b7c3',loss:'#ff8c98',line:'#ffffff12'};
const names={p:'Premiums',ni:'Net income',tm:'Medical expenses',a:'Administrative expenses'};
const escape=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const amount=v=>v==null?'N/A':(v<0?'−':'')+'$'+new Intl.NumberFormat('en-US',{maximumFractionDigits:2,minimumFractionDigits:Math.abs(v)>=1e9?2:0}).format(Math.abs(v)/(Math.abs(v)>=1e9?1e9:Math.abs(v)>=1e6?1e6:Math.abs(v)>=1e3?1e3:1))+(Math.abs(v)>=1e9?'B':Math.abs(v)>=1e6?'M':Math.abs(v)>=1e3?'K':'');
const exact=v=>v==null?'N/A':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v);
const count=v=>v.toLocaleString('en-US'),sum=(rows,key)=>rows.reduce((n,r)=>n+(r[key]||0),0);
function period(){return periods[state.period];}
function source(){return state.period==='q1'?data.planilla.sourceQ12026:state.period==='25'?data.planilla.sourceAnnual2025:data.planilla.sourceAnnual2024;}
function sourceLink(url,text){return '<a href="'+escape(url)+'" target="_blank" rel="noopener noreferrer">'+escape(text)+' ↗</a>';}
function text(id,value){$(id).textContent=value;}
function toast(msg){let n=document.createElement('div');n.className='toast';n.setAttribute('role','status');n.textContent=msg;document.body.append(n);setTimeout(()=>n.remove(),4000);}
function makeTable(headers,rows){return '<table><thead><tr>'+headers.map(t=>'<th>'+escape(t)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map((v,i)=>'<td>'+v+'</td>').join('')+'</tr>').join('')+'</tbody></table>';}
function renderChart(id,rows,paired){
 const el=$(id);if(!window.echarts){el.innerHTML='<div class="state"><strong>Chart could not load</strong><p>The figures remain available under Exact values. Reload the page to retry.</p></div>';return;}
 let chart=charts.get(id),fresh=!chart;if(!chart){el.innerHTML='';chart=echarts.init(el,null,{renderer:'svg'});charts.set(id,chart);if(!paired)chart.on('click',p=>{if(p.data?.entity)openInsurer(p.data.entity);});}
 chart.resize();const width=el.clientWidth,small=width<440,rowHeight=el.clientHeight/rows.length;
 const minimum=Math.min(0,...rows.map(r=>r.value||0)),maximum=Math.max(...rows.map(r=>Math.max(r.value||0,r.claims||0))),max=maximum||1,low=minimum<0?minimum*1.07:0,high=max*1.02;
 const left=0,right=0,plotWidth=width-left-right,x=v=>left+(v-low)/(high-low)*plotWidth,zero=x(0);
 const option={animation:!reduced&&fresh,animationDuration:500,animationDurationUpdate:0,animationEasing:'cubicOut',aria:{enabled:true,label:{description:(paired?'Premiums written and claims paid for ten coverage categories. ':'Insurer '+names[state.metric]+'. ')+period().label+'. Exact values are available in the table below.'}},tooltip:{trigger:'item',showDelay:0,hideDelay:50,confine:true,backgroundColor:'#080d12',borderColor:'#465660',textStyle:{color:color.ink,fontSize:13},extraCssText:'max-width:320px;white-space:normal;line-height:1.7;border-radius:6px;',formatter:p=>{const r=p.data,head='<b>'+escape(r.name)+'</b><br>'+period().label+' · OCS filing<br>';return head+(paired?'Premiums: '+exact(r.value[1])+'<br>Claims paid: '+exact(r.claims)+'<br>Paid claims / premiums: '+(r.claims/r.value[1]*100).toFixed(1)+'%':names[state.metric]+': '+exact(r.value[1])+(state.metric==='p'?'<br>Share of nine insurers: '+(r.value[1]/sum(data.insurers,'p'+state.period)*100).toFixed(1)+'%':'')+'<br>Select for financial details');}},grid:{left:0,right:0,top:0,bottom:0},xAxis:{show:false,min:low,max:high},yAxis:{show:false,min:0,max:rows.length},series:[{type:'custom',coordinateSystem:'none',id:paired?'coverage':'insurer',renderItem:(params,api)=>{const r=rows[params.dataIndex],y=params.dataIndex*rowHeight,barY=y+34,textSize=small?12:14,negative=r.value<0,barStart=Math.min(zero,x(r.value||0)),barWidth=Math.abs(x(r.value||0)-zero),children=[];
 // Names and values share each row. Common linear scale is used for every bar.
 children.push({type:'text',style:{text:r.name,x:0,y:y+6,fill:color.ink,font:'500 '+textSize+'px Inter, Arial, sans-serif',width:Math.max(100,width-(small?80:110)),overflow:'break',lineHeight:15,height:30}});
 children.push({type:'text',style:{text:amount(r.value),x:width,y:y+6,textAlign:'right',fill:negative?color.loss:color.ink,font:'600 '+(small?12:14)+'px Inter, Arial, sans-serif'}});
 children.push({type:'rect',shape:{x:0,y:barY,width:width,height:paired?16:10,r:2},style:{fill:'#ffffff05'}});
 if(r.value!=null){children.push({type:'rect',shape:{x:barStart,y:barY,width:barWidth,height:paired?7:10,r:2},style:{fill:negative?color.loss:color.teal}});}
 if(paired)children.push({type:'rect',shape:{x:zero,y:barY+9,width:Math.max(0,x(r.claims)-zero),height:7,r:2},style:{fill:color.neutral}});
 if(minimum<0)children.push({type:'line',shape:{x1:zero,y1:barY-2,x2:zero,y2:barY+12},style:{stroke:color.muted,lineWidth:1}});
 children.push({type:'line',shape:{x1:0,y1:y+rowHeight-6,x2:width,y2:y+rowHeight-6},style:{stroke:color.line,lineWidth:1}});
 // Full-row hit target also covers small bars and negative values.
 children.push({type:'rect',shape:{x:0,y:y,width,height:rowHeight-5},style:{fill:'rgba(0,0,0,0.001)'},cursor:paired?'default':'pointer'});
 return {type:'group',children};},data:rows.map((r,i)=>({name:r.name,entity:r.id,claims:r.claims,value:[i,r.value]}))}]};chart.setOption(option,{notMerge:true});
}
function render(){
 const p=period(),m=data.planilla.market[p.key],previous=data.planilla.market.FY24;
 document.documentElement.dataset.period=state.period;$('#period-panel').setAttribute('aria-labelledby','tab-'+state.period);document.querySelectorAll('[data-period]').forEach(b=>{let active=b.dataset.period===state.period;b.setAttribute('aria-selected',active);b.tabIndex=active?0:-1;});document.querySelectorAll('.period-label').forEach(n=>n.textContent=p.label);text('#period-note',p.note);
 [['premium','prem'],['claims','claims'],['lives','lives']].forEach(([id,k])=>{text('#'+id+'-kpi',k==='lives'?count(m[k]):amount(m[k]));const n=$('#'+id+'-note');n.className=state.period==='25'?'delta':'';n.textContent=state.period==='25'?'+'+((m[k]/previous[k]-1)*100).toFixed(1)+'% vs 2024':k==='lives'?'OCS reported covered lives':state.period==='q1'?'Three months · not annualized':'January–December total';});
 const coverage=data.planilla.coverage[p.key].slice().sort((a,b)=>b.prem-a.prem);renderChart('#coverage-chart',coverage.map(r=>({name:r.t,value:r.prem,claims:r.claims})),true);
 text('#coverage-caption','Claims paid = '+(m.claims/m.prem*100).toFixed(1)+'% of written premiums. This is not statutory MLR.');$('#coverage-source').href=source();$('#coverage-table').innerHTML=makeTable(['Coverage','Premiums','Claims paid','Covered lives'],coverage.map(r=>[escape(r.t),exact(r.prem),exact(r.claims),count(r.lives)]));
 $('#metric').disabled=state.period==='q1';$('#insurer-values').hidden=state.period==='q1';
 if(state.period==='q1'){const c=charts.get('#insurer-chart');if(c){c.dispose();charts.delete('#insurer-chart');}$('#insurer-chart').innerHTML='<div class="state"><span>Q1 2026</span><strong>Quarterly insurer results<br>are not available yet.</strong><p>The OCS report provides market and coverage totals. Matched financial statements for the nine insurers are not included in this dataset.</p></div>';text('#insurer-caption','Annual figures are not substituted for quarterly results.');}
 else{const rows=data.insurers.slice().sort((a,b)=>(b[state.metric+state.period]??-Infinity)-(a[state.metric+state.period]??-Infinity));renderChart('#insurer-chart',rows.map(r=>({id:r.id,name:r.n,value:r[state.metric+state.period]})),false);$('#insurer-chart').setAttribute('aria-label',names[state.metric]+' by insurer, '+p.label);text('#insurer-caption',(state.metric==='a'||state.metric==='tm'?'MCS Life: N/A — different filing form. ':'')+'Select a row for financial details.');$('#insurer-table').innerHTML=makeTable(['Insurer',names[state.metric]],rows.map(r=>['<button data-insurer="'+r.id+'">'+escape(r.n)+'</button>',exact(r[state.metric+state.period])]));}
 text('#status',p.label+' selected. Market figures and insurer comparison updated.');
}
function openInsurer(id){if(state.period==='q1')return;const d=data.insurers.find(r=>r.id===id);if(!d)return;const y=state.period,p=d['p'+y],ni=d['ni'+y];text('#detail-eyebrow',period().label+' · Statutory filing');$('#detail-body').innerHTML='<h2>'+escape(d.n)+'</h2><p>'+escape(d.le)+'</p><dl class="detail-metrics">'+[['Premiums',exact(p)],['Net income',exact(ni),ni<0],['Medical expenses',exact(d['tm'+y])],['Administrative expenses',exact(d['a'+y])],['Share of nine insurers',(p/sum(data.insurers,'p'+y)*100).toFixed(1)+'%'],['Net income / premiums',(ni/p*100).toFixed(1)+'%',ni<0]].map(r=>'<div><dt>'+r[0]+'</dt><dd'+(r[2]?' class="loss"':'')+'>'+r[1]+'</dd></div>').join('')+'</dl><p>'+(d.id==='mcsl'?'MCS Life uses a Life filing form. Its medical and administrative expense fields are not comparable with the eight Health filings.':'Net income includes items beyond premiums, medical expenses and administration. These amounts do not form a simple expense bridge.')+'</p><p class="filing-link">'+sourceLink(d['s'+y],'Open original OCS filing')+'</p>';$('#detail-dialog').showModal();}
function showSources(){const p=period();$('#sources-body').innerHTML='<p>These are the existing Observatory datasets. Market coverage and insurer statements have different reporting scopes.</p><h3>Market & coverage · '+p.label+'</h3><p>'+sourceLink(source(),'OCS Health Insurance Report')+'</p>'+(state.period==='25'?'<p>The claims total follows the detailed coverage table on PDF page 2; it exceeds the page 8 summary by $196,246, as documented in the existing Observatory.</p>':'')+'<h3>Insurer financial statements</h3>'+(state.period==='q1'?'<p>No matched Q1 2026 insurer statements in this dataset.</p>':'<ul>'+data.insurers.map(d=>'<li>'+sourceLink(d['s'+state.period],d.n)+'</li>').join('')+'</ul>')+'<p>2024 values are as filed for 2024. No monthly series or quarterly insurer values have been inferred.</p>';$('#sources-dialog').showModal();}
function exportCSV(){const p=period(),rows=[['Period','Scope','Entity','Premiums USD','Claims paid USD','Covered lives','Net income USD','Medical expenses USD','Administrative expenses USD','Source']];data.planilla.coverage[p.key].forEach(r=>rows.push([p.label,'OCS market coverage',r.t,r.prem,r.claims,r.lives,'','','',r.src||source()]));if(state.period!=='q1')data.insurers.forEach(r=>rows.push([p.label,'Statutory insurer',r.le,r['p'+state.period],'','',r['ni'+state.period],r['tm'+state.period],r['a'+state.period],r['s'+state.period]]));const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='PR-insurance-'+p.label.replace(/ /g,'-')+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);toast(p.label+' data exported.');}
 document.querySelectorAll('[data-period]').forEach(b=>b.addEventListener('click',()=>{state.period=b.dataset.period;render();}));$('#metric').addEventListener('change',e=>{state.metric=e.target.value;render();});$('#sources-open').addEventListener('click',showSources);$('#export').addEventListener('click',exportCSV);document.addEventListener('click',e=>{const b=e.target.closest('[data-insurer]');if(b)openInsurer(b.dataset.insurer);if(e.target.closest('[data-close]'))e.target.closest('dialog').close();});document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));document.addEventListener('keydown',e=>{if(!e.target.matches('[role=tab]'))return;let tabs=[...document.querySelectorAll('[role=tab]')],i=tabs.indexOf(e.target),next=e.key==='ArrowRight'?(i+1)%3:e.key==='ArrowLeft'?(i+2)%3:e.key==='Home'?0:e.key==='End'?2:null;if(next!=null){e.preventDefault();tabs[next].click();tabs[next].focus();}});
let timer;window.addEventListener('resize',()=>{clearTimeout(timer);timer=setTimeout(render,100);});
window.ObservatoryPreview={render,state,charts,openInsurer};render();
})();
